name: MineCore
version: "1.0.0"
main: dk.mineclub.minecore.platform.paper.MineCorePaperPlugin
description: "MineCore Plugin er et plugin til at forbinde MineCore med Paper platformen."
api-version: "1.19"
loader: dk.mineclub.minecore.platform.paper.MineCorePaperLoader
dependencies:
    server:
        # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
        Skript:
            load: BEFORE
            required: false
            # This means that your plugin will not have access to their classpath
            join-classpath: true
