name: MineCore
version: "${version}"
main: dk.mineclub.minecore.platform.paper.MineCorePaperPlugin
api-version: "1.19"
author: MineClub
description: Paper platform module for MineCore
softdepend:
    - Skript
