[versions]
shadow = "9.4.2"
spotless = "8.7.0"
mavenPublish = "0.36.0"
resourceFactoryVelocity = "1.3.1"
okhttp = "5.4.0"
gson = "2.14.0"
socketclient = "2.1.2"
lombok = "1.18.46"
json = "20250517"
okio = "3.17.0"
jspecify = "1.0.0"
velocity = "3.5.0-SNAPSHOT"

[plugins]
shadow = {id = "com.gradleup.shadow", version.ref = "shadow"}
spotless = {id = "com.diffplug.spotless", version.ref = "spotless"}
maven-publish = {id = "com.vanniktech.maven.publish", version.ref = "mavenPublish"}
resource-factory-velocity = {id = "xyz.jpenilla.resource-factory-velocity-convention", version.ref = "resourceFactoryVelocity"}

[libraries]
okhttp = {group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
socketclient = {group = "io.socket", name = "socket.io-client", version.ref = "socketclient"}
lombok = {group = "org.projectlombok", name = "lombok", version.ref = "lombok"}
json = {group = "org.json", name = "json", version.ref = "json"}
okio = {group = "com.squareup.okio", name = "okio", version.ref = "okio"}
jspecify = {group = "org.jspecify", name = "jspecify", version.ref = "jspecify"}
velocity = {group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity"}