[versions]
spotless = "8.8.0"
shadow = "9.5.1"
mavenPublish = "0.37.0"
resourceFactoryVelocity = "1.3.1"
okhttp = "5.4.0"
gson = "2.14.0"
socketclient = "2.1.2"
lombok = "1.18.46"
velocity = "3.5.0-SNAPSHOT"
packetevents = "2.13.0"
jedis = "7.5.3"
guava = "33.6.0-jre"
json = "20250517"
skriptnew = "2.15.3"
skript213 = "2.13.2"
skript295 = "2.9.5"
skript22dev36 = "dev36"

[plugins]
shadow = {id = "com.gradleup.shadow", version.ref = "shadow"}
spotless = {id = "com.diffplug.spotless", version.ref = "spotless"}
maven-publish = {id = "com.vanniktech.maven.publish", version.ref = "mavenPublish"}
resource-factory-velocity = {id = "xyz.jpenilla.resource-factory-velocity-convention", version.ref = "resourceFactoryVelocity"}

[libraries]
okhttp = {group = "com.squareup.okhttp3", name = "okhttp-jvm", version.ref = "okhttp"}
gson = {group = "com.google.code.gson", name = "gson", version.ref = "gson"}
socketclient = {group = "io.socket", name = "socket.io-client", version.ref = "socketclient"}
lombok = {group = "org.projectlombok", name = "lombok", version.ref = "lombok"}
velocity = {group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity"}
packetevents-api = {group = "com.github.retrooper", name = "packetevents-api", version.ref = "packetevents"}
jedis = {module = "redis.clients:jedis", version.ref = "jedis"}
guava = {group = "com.google.guava", name = "guava", version.ref = "guava"}
json = {group = "org.json", name = "json", version.ref = "json"}
skriptnew = {group = "com.github.SkriptLang", name = "Skript", version.ref = "skriptnew"}
skript213 = {group = "com.github.SkriptLang", name = "Skript", version.ref = "skript213"}
skript295 = {group = "com.github.SkriptLang", name = "Skript", version.ref = "skript295"}
skript22dev36 = {group = "com.github.SkriptLang", name = "Skript", version.ref = "skript22dev36"}
