name: MineCore
version: "${version}"
main: dk.mineclub.minecore.platform.bukkit.MineCoreBukkitPlugin
api-version: "1.13"
author: MineClub
description: Bukkit platform module for MineCore
softdepend:
    - Skript
